// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqgNOakgPEmMSTQNpDYSedUemyjPs5qjc',
    appId: '1:510881357803:web:56fc4be4398a2a820343ae',
    messagingSenderId: '510881357803',
    projectId: 'chat-app-68762',
    authDomain: 'chat-app-68762.firebaseapp.com',
    storageBucket: 'chat-app-68762.firebasestorage.app',
    measurementId: 'G-78VZTDXP8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXzJB_w0FRrRqQJ6_B3Ygi7g-eb6_34ck',
    appId: '1:510881357803:android:553983961e285c750343ae',
    messagingSenderId: '510881357803',
    projectId: 'chat-app-68762',
    storageBucket: 'chat-app-68762.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPWnZJ07zIsB1XE3la2lKExXqFHSwFN5Q',
    appId: '1:510881357803:ios:25110f441381c0980343ae',
    messagingSenderId: '510881357803',
    projectId: 'chat-app-68762',
    storageBucket: 'chat-app-68762.firebasestorage.app',
    iosBundleId: 'com.example.simpleChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPWnZJ07zIsB1XE3la2lKExXqFHSwFN5Q',
    appId: '1:510881357803:ios:25110f441381c0980343ae',
    messagingSenderId: '510881357803',
    projectId: 'chat-app-68762',
    storageBucket: 'chat-app-68762.firebasestorage.app',
    iosBundleId: 'com.example.simpleChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqgNOakgPEmMSTQNpDYSedUemyjPs5qjc',
    appId: '1:510881357803:web:68932f5d7c239bfe0343ae',
    messagingSenderId: '510881357803',
    projectId: 'chat-app-68762',
    authDomain: 'chat-app-68762.firebaseapp.com',
    storageBucket: 'chat-app-68762.firebasestorage.app',
    measurementId: 'G-LGQZCS4YK1',
  );
}
